{application,web,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,n2o,hackney,instagram]},
              {mod,{web_app,[]}},
              {env,[]},
              {modules,[index,index_view,post_callback,routes,web_app,
                        web_sup]}]}.
